version: "3.9"

services:
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
  redis:
    restart: always
    image: redis:6.0.1
    ports:
      - 6379:6379
    networks:
      - travlr

  rabbitmq:
    restart: always
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_ERLANG_COOKIE=1WqgH8N2v1qDBDZDbNy8Bg9IkPWLEpu79m6q+0t36lQ=
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - travlr

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    restart: always
    volumes:
      - C:/Users/igrwi/Workspace/Infrastructure/DockerVolume/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - travlr

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - travlr

  apm:
    image: docker.elastic.co/apm/apm-server:7.15.0
    restart: always
    volumes:
      - ./configs/apm-server.yml:/usr/share/apm-server/apm-server.yml
    environment:
      - output.elasticsearch.hosts=http://elasticsearch:9200
      - BEAT_STRICT_PERMS=false
    ports:
      - "8200:8200"
    depends_on:
      - elasticsearch
    networks:
      - travlr

  mysql:
    image: mysql:5.7
    hostname: db
    restart: always
    command: --max_allowed_packet=1073741824
    volumes:
      - C:/Users/igrwi/Workspace/Infrastructure/DockerVolume/MySql57:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - 3306:3306
    networks:
      - travlr

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 9001:80
    networks:
      - travlr
    environment:
      - "UPLOAD_LIMIT=2G"
      - "PMA_HOST=db"
      - "PMA_PASSWORD=root"
    depends_on:
      - mysql

  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - C:/Users/igrwi/Workspace/TRAVLR/Repo/thebalibible:/app/public/tbb
      - C:/Users/igrwi/Workspace/TRAVLR/Repo/thebalibible-cms:/app/public/tbb-cms
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - php-web
    depends_on:
      - php-fpm

  php-fpm:
    container_name: php-fpm
    build:
      context: .
      dockerfile: TravlrPHP.Dockerfile
    volumes:
      - C:/Users/igrwi/Workspace/TRAVLR/Repo/thebalibible:/app/public/tbb
      - C:/Users/igrwi/Workspace/TRAVLR/Repo/thebalibible-cms:/app/public/tbb-cms
    networks:
      - php-web

networks:
  travlr:
    driver: bridge
  php-web:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
